### ISSUE TITLE
Reference Error: Can't find variable: touchId

### ISSUE THREAD

**Issue by dalefrancis88** [leecrossley/cordova-plugin-touchid#12]
Hey,

I am trying to get touch id working on my ionic/cordova app and when i run i am getting the error above. I have tried re-installing the plugin, i have done multiple builds, i have even removed and re-added the ios platform for that project and none of it seems to fix the error.

Do you have any thoughts?

Dale

**Comment by leecrossley** [comment]
This is after `deviceready` has been called?

**Comment by leecrossley** [comment]
Also, `touchid` is all lowercase
