### ISSUE TITLE
Totally white screen when I attempt to use the library

### ISSUE THREAD

**Issue by Timidger** [leecrossley/cordova-plugin-touchid#18]
My app uses Cordova and React, and whenever I build the app with Xcode and run it on my device (iphone 5s) the app isn't loaded at all and all I get is a white screen. It doesn't matter where I put the function calls, but as soon I take them out the app starts working again normally.

**Comment by drewcovi** [comment]
Is cordova.js loaded?  I'd check by running the exported HTML in safari. That is typically what I've seen.

**Comment by Timidger** [comment]
Yep, cordova.js is loaded. It looks like everything is loaded, but the only html is loaded are some custom scripts I use for tracking, the app itself, and cordova.js. No console output to indicate anything is wrong either.

**Comment by Timidger** [comment]
Hmm, I think it was a problem with plugman. Thanks anyways, sorry for wasting your time.
