### ISSUE TITLE
Closing Touch ID authentication through code

### ISSUE THREAD

**Issue by vaibhav-khopade** [leecrossley/cordova-plugin-touchid#5]
Hi

Is it possible to close Touch ID authentication dialog through program ?

**Comment by leecrossley** [comment]
I'm not entirely sure what you're asking for. If it's to be able to close the dialog via a javascript interface in your webview, then it's not possible.

**Comment by vaibhav-khopade** [comment]
Hi 
Thanks for quick reply. That is what i want to do. Sometimes I want to force close TouchID dialog. Or I want to generate System Cancel event programmatically.
