### ISSUE TITLE
iOS 9 bug

### ISSUE THREAD

**Issue by linkito** [leecrossley/cordova-plugin-touchid#9]
Hi.

I have the iOS 9 Beta, and since the first beta version, the TouchID plugin has an issue of a bucle prompt of TouchID... When its success, the prompt message appears again, and again, and again....

I think that is an issue of the pluggin, and not of the beta.

Greetings

**Comment by leecrossley** [comment]
Thanks for reporting this @linkito. I'll leave the issue open but won't look at it until nearer the release, as these kind of things do tend to change between betas.

**Comment by linkito** [comment]
Sure! Maybe is an error of the beta version :). If in the RC of iOS 9 still this bug, I report you again :)
Thanks a lot for your work in this plugin :+1:

**Comment by linkito** [comment]
Hi again.

This seems to be an error of Angular and iOS 9:
https://gist.github.com/IgorMinar/863acd413e3925bf282c

Maybe your plugin haven't any problem, only Angular :)

Greetings
